### PR TITLE
Better 404 Handling

### PR DESCRIPTION
**Pull request by chelm**
Just adding a check for statusCode on responses from CKAN

### CODE REVIEW

**Comment by chelm** [comment]
Closes #5

**Comment by jgravois** [comment]
saweet.  dmart and i will make sure to update the provider readme with new test urls too.

**Comment by jgravois** [comment]
@dmartine and i will test/merge this PR as well.

**Comment by jgravois** [comment]
looks good.

koop now responds with
```
Unable to retrieve data from https://data.hdx.rwlabs.org/datastore/dump/45771200-34c9-4d0d-9a88-7c58512af19b
```
@dmartine will follow up with an additional PR once he tracks down the latest airport data.

**Comment by chelm** [comment]
@jgravois I'm revisiting this issue for #8 and wondering why the 404 on this dataset appeared in the first place. Can't seem to remember.

**Pull request merged**
